"""Create issuance tables

Revision ID: 547f38339c0c
Revises: 089c7f184c48
Create Date: 2026-10-01 10:59:15.329106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547f38339c0c'
down_revision: Union[str, Sequence[str], None] = '089c7f184c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issued_to_user_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expected_return_date', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issued_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issuances_id'), 'issuances', ['id'], unique=False)
    op.create_index(op.f('ix_issuances_issued_by_user_id'), 'issuances', ['issued_by_user_id'], unique=False)
    op.create_index(op.f('ix_issuances_issued_to_user_id'), 'issuances', ['issued_to_user_id'], unique=False)
    op.create_table('issuance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuance_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuances.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issuance_items_asset_id'), 'issuance_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_issuance_items_id'), 'issuance_items', ['id'], unique=False)
    op.create_index(op.f('ix_issuance_items_issuance_id'), 'issuance_items', ['issuance_id'], unique=False)
    op.create_index(op.f('ix_issuance_items_product_id'), 'issuance_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issuance_items_product_id'), table_name='issuance_items')
    op.drop_index(op.f('ix_issuance_items_issuance_id'), table_name='issuance_items')
    op.drop_index(op.f('ix_issuance_items_id'), table_name='issuance_items')
    op.drop_index(op.f('ix_issuance_items_asset_id'), table_name='issuance_items')
    op.drop_table('issuance_items')
    op.drop_index(op.f('ix_issuances_issued_to_user_id'), table_name='issuances')
    op.drop_index(op.f('ix_issuances_issued_by_user_id'), table_name='issuances')
    op.drop_index(op.f('ix_issuances_id'), table_name='issuances')
    op.drop_table('issuances')
    # ### end Alembic commands ###
