"""Create return tables

Revision ID: 869eabb0389f
Revises: 547f38339c0c
Create Date: 2026-10-01 11:08:02.859696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869eabb0389f'
down_revision: Union[str, Sequence[str], None] = '547f38339c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuance_id', sa.Integer(), nullable=False),
    sa.Column('received_by_user_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuance_id'], ['issuances.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_id'), 'returns', ['id'], unique=False)
    op.create_index(op.f('ix_returns_issuance_id'), 'returns', ['issuance_id'], unique=False)
    op.create_index(op.f('ix_returns_received_by_user_id'), 'returns', ['received_by_user_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('issuance_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issuance_item_id'], ['issuance_items.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_id'), 'return_items', ['id'], unique=False)
    op.create_index(op.f('ix_return_items_issuance_item_id'), 'return_items', ['issuance_item_id'], unique=False)
    op.create_index(op.f('ix_return_items_return_id'), 'return_items', ['return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_items_return_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_issuance_item_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_returns_received_by_user_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_issuance_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_id'), table_name='returns')
    op.drop_table('returns')
    # ### end Alembic commands ###
