"""Add item type to products

Revision ID: da54682abab6
Revises: 42592bf568f5
Create Date: 2026-10-01 09:59:17.218739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da54682abab6'
down_revision: Union[str, Sequence[str], None] = '42592bf568f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_type', sa.String(length=20), nullable=False, server_default='CONSUMABLE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'item_type')
    # ### end Alembic commands ###
